name: technicaltest_danafix
version: 1.0.0+1
publish_to: none
description: Technical Test from DanaFix
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: 3.0.1
  dio: 4.0.6
  pull_to_refresh: ^2.0.0
  intl: 0.17.0
  webview_flutter: ^3.0.4
  connectivity_plus: 2.3.5
  provider: 6.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/

